app/models.py
from enum import unique
from operator import index
from re import S, T
import re
from flask.globals import request
from sqlalchemy.orm import backref, defaultload
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin, AnonymousUserMixin
from . import login_manager
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask import current_app
from . import db
from datetime import datetime, timezone
import hashlib
from markdown import markdown
import bleach

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(db.Model, UserMixin):

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(120), unique=True, nullable=False)
    username = db.Column(db.String(20), unique=True, nullable=True)
    password_hash = db.Column(db.String(128))
    name = db.Column(db.String(64))
    location = db.Column(db.String(64))
    about_me = db.Column(db.Text())
    avatar_hash = db.Column(db.String(32))

    def __init__(self, **kwargs):
        super(User, self).__init__(**kwargs)
        if self.email is not None and self.avatar_hash is None:
            #Se guarda el hash en el espacio del usuario, esto con la funcion que devuelve el hash
            self.avatar_hash = self.gravatar_hash()
            db.session.commit()
    
    #Funciono para hacer el hash con el email para el avatar
    def gravatar_hash(self):
        return hashlib.md5(self.email.lower().encode('utf-8')).hexdigest()


    #Funcion para genera avatar

    def gravatar(self, size=100, default='identicon', rating='g'):
        """
        if request.is_secure:
            url = 'https://secure.gravatar.com/avatar'
        else:
            url = 'http://www.gravatar.com/avatar'
        """
        url = 'https://secure.gravatar.com/avatar'
        hash = self.avatar_hash or self.gravatar_hash() 
        return '{url}/{hash}?s={size}&d={default}&r={rating}'.format(url=url, hash=hash, size=size, default=default, rating=rating)
    #Se hace un atributo en el cual se guarda la clave en cadena sencilla
    
    #Si se intenta leer no se va a poder porque va a dar un error
    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')
    
    #Entonces cuando se establece o se pone un valor en el atributo, se da la siguiente funcion
    @password.setter
    #La funcion con el mismo nombre del metodo, pero con la unica diferencia de que el parametro "password" es un atributo
    #Entonces cuando se sobreescribe el atributo, este sobreescribe otro atributo que sería el password_hash y lo que mete ahi es la contraseña de hash
    #que sería el atributo password que se genera un hash
    def password(self, password):
        #Guarda en su espacio/variable el hash del atributo password
        self.password_hash = generate_password_hash(password)

    #Este metodo lo que hace es tomar  la palabra para verificar si es la misma, si son iguales los hash entonces es correcto
    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return '<User %r>' % self.username

class Tool(db.Model):

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(30), unique=False, nullable=False)
    link = db.Column(db.String(220), unique=False, nullable=False)
    category = db.Column(db.String(30), unique=False, nullable=False)
    category = db.Column(db.Integer, db.ForeignKey('category.id'))
    image_tool = db.Column(db.String(20), unique=False, nullable=False)
    tool = db.relationship('UserTool', backref='user_tool')
    image_preview = db.Column(db.String(20), unique=False, nullable=False)
    descripcion = db.Column(db.String(1000), unique=False, nullable=False)
    type_tool = db.Column(db.String(20), unique=False, nullable=False)


class UserTool(db.Model):

    id = db.Column(db.Integer, primary_key=True)
    users_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    tool_id = db.Column(db.Integer, db.ForeignKey('tool.id'))

class Category(db.Model):

    id = db.Column(db.Integer, primary_key=True)
    category_name = db.Column(db.String(20), unique=True, nullable=False)
    image_category = db.Column(db.String(30), unique=False, nullable=True)
    type_category_id = db.Column(db.Integer, db.ForeignKey('type.id'))
    url_for_category = db.Column(db.String(30), unique=True, nullable=True)
    category_id = db.relationship('Tool', backref='category_name')

class Type(db.Model):

    id = db.Column(db.Integer, primary_key=True)
    name_type = db.Column(db.String(30), unique=True, nullable=False)
    type_ca = db.relationship('Category', backref='type_ca')

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.fields.simple import TextAreaField
from wtforms.validators import DataRequired, Length


class NameForm(FlaskForm):
    name = StringField('Cuál es tu nombre?', validators=[DataRequired()])
    submit = SubmitField('Submit')

class EditProfile(FlaskForm):
    name = StringField('Nombre Real', validators=[Length(0, 64)])
    location = StringField('Lugar', validators=[Length(0, 64)])
    about_me = TextAreaField('Acerca de mi')
    submite = SubmitField('Enter')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from config import config
from flask_login import LoginManager
from flask_migrate import Migrate


bootstrap = Bootstrap()
mail = Mail()
moment = Moment()
db = SQLAlchemy()


login_manager = LoginManager()
login_manager.login_view = 'auth.login'

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)


    bootstrap.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    #Registro del modelo principal para las rutas principales
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    
    # Registro del modelo de autenticación
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    login_manager.init_app(app)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from logging import error
from operator import pos
import re
from flask import render_template, session, redirect, url_for, current_app
from flask.globals import request
from flask.helpers import flash
from .. import db
from ..models import User
from ..email import send_email
from . import main
from .forms import NameForm, EditProfile
from datetime import datetime
from flask_login.utils import login_required, login_user, logout_user, current_user

@main.before_request
def before_request():
    endpoint = request.endpoint
    endpoint=endpoint[5:]
    session['ruta']= endpoint
    
@main.route('/', methods=['GET', 'POST'])
def index():
    return render_template('index.html')

@main.route('/askName', methods=['GET', 'POST'])
def askName():
    form = NameForm()
    if form.validate_on_submit():
        old_name = session.get('name')
        if old_name is not None and old_name != form.name.data:
            flash('Looks like you have changed your name! ')
        session['name'] = form.name.data
        return redirect(url_for('.askName'))
    return render_template('askName.html', form=form, name = session.get('name'))

@main.route('/user/<username>')
def user(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        return render_template('errorHandlers/404.html')
    return render_template('profile.html', user=user)


@main.route('/editar-perfil', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfile()
    user = current_user.username
    #print(user)
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.location = form.location.data
        current_user.about_me = form.about_me.data
        #db.session.add(current_user.__get_current_object())
        db.session.commit()
        flash('Your profile has been updated')
        return redirect(url_for('main.user', username=current_user.username))
    form.name.data = current_user.name
    form.location.data = current_user.location
    form.about_me.data = current_user.about_me
    return render_template('edit_profile.html', form=form, user=user)

# @main.route('/post/<int:id>')
# def post(id):
#     post = Post.query.get_or_404(id)
#     return render_template('post.html', posts=[post])

@main.route('/prueba')
def prueba():
    return render_template('prueba.html')

app/templates/_macros.html
<style>
    div.pagination {
    width: 100%;
    text-align: right;
    padding: 0px;
    margin: 0px;
}
</style>

{% macro pagination_widget(pagination, endpoint) %}
<ul class="pagination">
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{% else %}#{% endif %}">
            &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

app/templates/_posts.html
<div class="container">
    <ul class="posts">
        {% for post in posts %}
        <li class="post">
            <div class="post-thumbnail">
                <a href="{{ url_for('.user', username=post.author.username) }}">
                    <img class="img-rounded profile-thumbnail" src="{{ post.author.gravatar(size=39) }}">
                </a>
            </div>
            <div class="post-content">
                <div class="post-date"></div>
                <div class="post-author"><a href="{{ url_for('.user', username=post.author.username) }}">{{ post.author.username }}</a></div>
                <div class="post-body">
                    {% if post.body_html %}
                        {{ post.body_html | safe }}
                    {% else %}
                        {{ post.body }}
                    {% endif %}
                </div>
                <div class="post-footer">
                    <a href="{{ url_for('main.post', id=post.id) }}">
                        <span class="label label-default">Permalink</span>
                    </a>
                </div>
            </div>
        </li>
        {% endfor %}
    </ul>
</div>

app/templates/askName.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} <title> Yeah - Page Not Found </title>{% endblock %}

{% block page_content %}
<div class="page-header">
    <div class="container" style="color: white;">

        <h1>Hello, {% if name %}{{ name }}{% else %}Stranger{% endif %}</h1>
        {{ wtf.quick_form(form) }}
    </div>
</div>
{% endblock %}

app/templates/base.html
{% block title %}
Flasky
{% endblock %}

{% block head %}
<head>
<link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/stars.css') }}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
{% endblock %}
{% block styles %}
{% endblock %}
<body>
    <section class="wrapper">
        <div id="stars"></div>
        <div id="stars2"></div>
        <div id="stars3"></div>
    </section>
{% block navbar %}
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="background-color: transparent !important;">
        <div class="container">
            <a class="navbar-brand nav-link btn" href="{{ url_for('main.index') }}">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="btn nav-link" href="{{ url_for('main.index') }}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="btn nav-link " href="{{ url_for('main.user', username=current_user.username) }}">Profile</a>
                    </li>
                    <!-- <a class="btn nav-link" href="{{ url_for('main.edit_profile') }}">
                        Edit Profile
                    </a> -->
                    {% endif %}
                    <!-- <li class="nav-item">
                        <a class="nav-link disabled" href="#">Disabled</a>
                    </li> -->
                </ul>
                <div class="navbar-nav">
                    {% if current_user.is_authenticated %}
                        <!-- <a class="nav-item nav-link btn" href="{{ url_for('auth.logout') }}">Log out</a> -->
                        <li class="nav-item dropdown nav-item btn">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background-color: transparent !important;">
                                <img src="{{ current_user.gravatar(size=25) }}" style="margin-right: 8px; border-radius: 5px;">Account
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" style="background-color: transparent;">
                              <a class="nav-item nav-link btn" href="#">Change email</a>
                              <a class="nav-item nav-link btn" href="#">Change Password</a>
                              <a class="nav-item nav-link btn" href="{{ url_for('auth.logout') }}">Log out</a>
                            </div>
                          </li>
                    {% else %}
                        <a class="nav-item nav-link btn" href="{{ url_for('auth.login') }}">Log in</a>
                        <a class="nav-item nav-link btn" href="{{ url_for('auth.register') }}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header> 
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
</div>
    {% block page_content %}{% endblock %}

{% endblock %}
{% block scripts %}

    <!-- Archivos para bootstrap version 4.0.0 #La más estable -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <!-- ====================================================================================================================================================================================================== -->

    <!-- Importamos los archivos de esta libreria -->
    {{ moment.include_moment() }}
    <!-- Podemos seleccionar un lenguaje para que se vea en el archivo de esta libreria -->
    {{ moment.locale('es') }}

    <!-- ====================================================================================================================================================================================================== -->
{% endblock %}
</body>
</html>

app/templates/edit_profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} <title>Edit Profile's {{ user|capitalize }} - Flasky</title>{% endblock %}


{% block page_content %}
<div class="container" style="color:white;">
    <h1>Editar Perfil</h1>
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}<title>Flasky</title>{% endblock %}

{% block page_content %}
<div class="container">
    <div class="page-header">
        <h1 style="color: white;">Hola, {% if current_user.is_authenticated %}{{ current_user.username }}{% else %}Desconocido{% endif %}!</h1>
    </div>

</div>
{% endblock %}

app/templates/post.html
{% extends "base.html" %}
{% block title %} <title>Flasky - Post</title>{% endblock %}

{% block page_content %}
{% include "_posts.html" %}
{% endblock %}

app/templates/profile.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block title %} <title> Flasky - {{ user.username|capitalize }} </title>{% endblock %}

{% block page_content %}
<div class="page-header" >
    <div class="container" style="color: white;">
        <img class="img-rounded profile-thumbnail" src="{{ user.gravatar(size=256) }}" style="border-radius: 20px;">
        <div class="profile-header" style="display: inline-block;">
            <div style="margin-left: 2em; display: flexbox;">
                <h1>{{ user.username }}</h1>
                {% if user.name or user.location %}
                <p>
                    {% if user.name %}{{ user.name }}{% endif %}
                    {% if user.location %}
                        From <a href="http://maps.google.com/?q={{ user.location }}">
                            {{ user.location }}
                        </a>
                    {% endif %}
                </p>
                {% endif %}
                {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}

                {% if user == current_user %}
                <a href="{{ url_for('main.edit_profile') }}" class="btn btn-default" style="background-color: white;">
                    Editar Perfil
                </a>
                {% endif%}
        </div>
    </div>
</div>
<div class="container" style="margin-top: 2em;">
    <h2 style="color: white; display: flex; justify-content: center;">Favorites by {{ user.username }}</h2>
</div> 

{% endblock %}

app/templates/prueba.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block title %} <title>Prueba-Diseño</title>{% endblock %}

{% block page_content %}

<div class="container" style="margin-top: 2em;">
    <h2 style="color: white; display: flex; justify-content: center;">Diseño</h2>
</div> 

{% endblock %}